services:
  #Database
  franklin_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3319:3306
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: franklin_db
  #Web
  franklin_wp:
    depends_on:
      - franklin_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8084:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: franklin_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define( 'JETPACK_SIGNATURE__HTTPS_PORT', 0 );
        define( 'MEDIA_TRASH', true );
        define('EMPTY_TRASH_DAYS', 30); 
        define( 'PP_EDIT_EXCEPTIONS_ALLOW_ATTACHMENT_DELETION', true );
        define('DISALLOW_FILE_EDIT', true);
        define( 'WPCF7_ADMIN_READ_CAPABILITY', 'manage_options' );
        define( 'WPCF7_ADMIN_READ_WRITE_CAPABILITY', 'manage_options' );
        define( 'WP_MEMORY_LIMIT', '128M' );
    container_name: franklin_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  franklin_myadmin:
    image: phpmyadmin:latest
    container_name: franklin_myadmin
    restart: "no"
    ports:
      - 5005:80
    environment:
      PMA_HOST: franklin_db
      UPLOAD_LIMIT: 100M
    depends_on:
      - franklin_db
volumes:
  db_data:
  wp-content:
